import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import Product from "../models/Product"
import mongoose from "mongoose";
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Image src="/../public/MainBook2.webp" width={2000} height={800} className='w-auto h-100' alt="" /> 
      </div>

      <section className="text-gray-600 body-font">

        <div className="container px-2 py-8 mx-auto ">

          <div className="flex flex-col flex-wrap items-center w-full mb-20 text-center">
            <h1 className="mb-2 text-2xl font-medium sm:text-3xl title-font">Our Best Books</h1>
            <p className="w-full leading-relaxed lg:w-1/2">Books that likes by the most user</p>
          </div> 

            <div className='container flex py-8 mx-auto -m-4 overflow-x-scroll scrollbar-hide'>
              { products.map((item)=>{  
                return <Link passHref={true} key={item._id} href={`/product/${item.slug}`} legacyBehavior>
                    <div className="ml-5 text-center cursor-pointer md:p-2 lg:ml-5 lg:p-2 basis-1/2">
                      <div className="flex justify-center w-[11vh] md:w-[18vh] lg:w-[23vh]">
                        <Image alt="ecommerce" width={600} height={600} className="h-[17vh]  md:h-[28vh] lg:h-[32vh] inline-block md:block" src={item.img}/>
                      </div>
                      <div className="mt-5 ">
                        <h3 className="mb-1 text-xs tracking-widest text-gray-500 title-font">CATEGORY</h3>
                        <h2 className="text-lg font-medium text-gray-900 title-font">{item.title}</h2>
                        <p className="mt-1">&#x20B9; {item.price}</p>
                        {item.availableQty == 1 && <p className='mb-2 text-red-600 md:text-base'>Only 1 available in stock</p>}
                      </div>
                    </div>
                  </Link> 
                })
              }
            </div>

          <Link href={'/books'}><button className="flex px-8 py-2 mx-auto mt-16 text-lg text-white bg-blue-500 border-0 rounded focus:outline-none hover:bg-blue-600">See more</button></Link>
        
        </div>
      </section>

    </>
  )
}

export const getServerSideProps = async () => {
  
  if(!mongoose.connections[0].readyState){
    await mongoose.connect(process.env.MONGO_URI);
  }

  let products = await Product.find({ category: 'book' })

  return { props: { products: JSON.parse(JSON.stringify(products)) } }
} 